CREATE TABLE IF NOT EXISTS `rl_file` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`review_id` INT UNSIGNED NOT NULL,
	`state` TINYINT UNSIGNED DEFAULT NULL,
	`name` varchar(255) DEFAULT NULL,
	`remark` varchar(1024) DEFAULT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`review_id`) REFERENCES rl_review(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
