CREATE TABLE IF NOT EXISTS `rl_remark` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`file_id` INT UNSIGNED NOT NULL,
	`content` varchar(1024) DEFAULT NULL,
	`first_line` INT UNSIGNED DEFAULT NULL,
	`last_line` INT UNSIGNED DEFAULT NULL,
	`style` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`file_id`) REFERENCES rl_file(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
